# Generated by Django 5.2.15 on 2026-06-18 15:00

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestSnippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("comment", 1), ("text", 0)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.StructBlock", [[("text", 0), ("replies", 2)]], {}),
                            2: ("wagtail.blocks.ListBlock", (1,), {"required": False}),
                        },
                    ),
                ),
            ],
        ),
    ]
